model_version: v5
model_edit: 02
model_run: B
model_desc: "More Training Data. higher filter size."
learning_rate: 0.01
batch_size: 32
epoch: 30
conv1_filter: 16
conv2_filter: 32
conv1_kernal: 8
conv2_kernal: 4
fully_connected: 128
load: False
